"use strict";
var lname;
lname = "Adrian";
var newname = lname.toUpperCase();
console.log(newname);
var age;
age = 25;
age = 25.5;
console.log(age);
var isValid;
isValid = true;
console.log(isValid);
